// Dados que alimentam a geração automática das páginas de detalhe em /solucoes/*.html
// Editar uma solução aqui reflete no título, SEO, hero, seções e CTA da respectiva página.
module.exports = [
  {
    slug: "projetos-eletricos",
    title: "Projetos Elétricos | CG Elétrica",
    description: "Projetos elétricos, cálculos, dimensionamentos e orçamentos técnicos com responsabilidade profissional na CG Elétrica.",
    whatsappMessage: "Olá, gostaria de solicitar um projeto elétrico.",
    heroTitle: "Projetos elétricos",
    heroLead: "Planejamento técnico para instalações seguras, eficientes e adequadas ao uso pretendido.",
    benefitText: "Definição assertiva do escopo, materiais e infraestrutura antes da execução.",
    quandoText: "Quando a instalação precisa de reformulação, expansão, adequação ou projeto técnico completo, com base em demanda, cargas e condições do local.",
    executaList: [
      "Projetos elétricos e dimensionamentos;",
      "Cálculos e especificações técnicas;",
      "Levantamento de materiais e orçamento;",
      "Documentação para execução e gestão.",
    ],
    aplicacoesText: "Empreendimentos comerciais, industriais, condomínios, sistemas específicos e instalações com demanda técnica relevante.",
    processoList: [
      "Diagnóstico da demanda e das condições existentes;",
      "Levantamento técnico e definição do escopo;",
      "Cálculos e especificações do projeto;",
      "Elaboração de orçamento e documentação;",
      "Entrega para execução.",
    ],
    beneficiosList: [
      "Segurança e confiabilidade;",
      "Dimensionamento adequado aos equipamentos e cargas;",
      "Redução de retrabalhos e perdas;",
      "Melhor gestão da manutenção e operação.",
    ],
    responsabilidadeText: "O escopo é conduzido com rigor técnico e documentação conforme a necessidade do projeto, incluindo ART quando aplicável.",
    faq: [
      { pergunta: "Preciso de projeto para uma reforma?", resposta: "Sim, projetos elétricos são essenciais quando há adequações, ampliação ou troca de infraestrutura." },
      { pergunta: "O orçamento entra no escopo?", resposta: "Sim, a elaboração do orçamento pode ser parte do processo técnico." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "manutencao-subestacoes",
    title: "Manutenção de Subestações Elétricas | CG Elétrica",
    description: "Manutenção de subestações elétricas com inspeção, diagnóstico, prevenção de falhas e garantia de confiabilidade operacional para instalações críticas.",
    whatsappMessage: "Olá, gostaria de solicitar informações sobre manutenção de subestação elétrica.",
    heroTitle: "Manutenção de subestações elétricas",
    heroLead: "Soluções para manutenção preventiva e corretiva, inspeção e diagnóstico de instalações críticas.",
    benefitText: "Maior confiabilidade, menor risco de falhas e continuidade operacional das instalações.",
    quandoText: "Quando a instalação exige inspeção periódica, diagnóstico técnico, prevenção de falhas e garantia de disponibilidade operacional em sistemas sensíveis.",
    executaList: [
      "Manutenção preventiva e corretiva;",
      "Inspeções técnicas e diagnóstico de condições;",
      "Identificação de falhas e riscos operacionais;",
      "Condição de equipamentos, infraestrutura e proteção.",
    ],
    aplicacoesText: "Empresas, indústrias, condomínios, instalações comerciais e sistemas com requisitos de continuidade e segurança.",
    processoList: [
      "Levantamento das condições da instalação;",
      "Inspeção técnica e avaliação de componentes;",
      "Diagnóstico e indicação de correções;",
      "Execução do plano de manutenção;",
      "Entrega técnica com documentação.",
    ],
    beneficiosList: [
      "Segurança das instalações;",
      "Confiabilidade operacional;",
      "Prevenção de falhas e interrupções;",
      "Redução de riscos e aumento de vida útil de equipamentos.",
    ],
    responsabilidadeText: "Aplicável conforme escopo, conforme a legislação e a natureza da solução, com ART quando indicada.",
    faq: [
      { pergunta: "Qual a periodicidade ideal?", resposta: "Depende do tipo de instalação, do nível de criticidade e das condições operacionais." },
      { pergunta: "Quando a manutenção é urgente?", resposta: "Quando há falhas, aquecimento, ruído anormal, queda de tensão ou riscos de interrupção." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "eficiencia-energetica",
    title: "Eficiência Energética | CG Elétrica",
    description: "Diagnóstico de consumo, demanda e oportunidades de eficiência energética para empresas e instalações no Rio de Janeiro.",
    whatsappMessage: "Olá, gostaria de solicitar uma análise de eficiência energética.",
    whatsappMessageFinal: "Olá, gostaria de solicitar uma análise de eficiência energética para minha empresa.",
    heroTitle: "Eficiência energética",
    heroLead: "Análise técnica para reduzir desperdícios, melhorar a operação e racionalizar o consumo.",
    benefitText: "Otimização do uso de energia e melhor desempenho da instalação com base em dados e diagnóstico técnico.",
    quandoText: "Quando há aumento de custos, consumo elevado, demanda irregular, falhas operacionais ou oportunidade de ajuste na infraestrutura elétrica.",
    executaList: [
      "Análise de consumo e demanda;",
      "Avaliação de faturas e perfil de utilização;",
      "Diagnóstico de desperdícios e oportunidades;",
      "Recomendações técnicas para otimização.",
    ],
    aplicacoesText: "Comércios, indústrias, empreendimentos, condomínios, instalações com operação contínua e demandas técnicas relevantes.",
    processoList: [
      "Coleta de dados e contexto da instalação;",
      "Diagnóstico técnico de consumo e demanda;",
      "Identificação de oportunidades de melhoria;",
      "Definição de medidas e escopo;",
      "Entregável com orientação prática.",
    ],
    beneficiosList: [
      "Melhor uso da energia disponível;",
      "Redução racional de custos;",
      "Maior previsibilidade operacional;",
      "Estratégia alinhada à segurança e eficiência.",
    ],
    responsabilidadeText: "A solução é conduzida com análise técnica rigorosa e orientação de engenharia, sem promessas genéricas de resultados.",
    faq: [
      { pergunta: "É preciso ser grande para solicitar?", resposta: "Não. Qualquer instalação com consumo relevante pode se beneficiar da análise." },
      { pergunta: "Qual o objetivo da análise?", resposta: "Entender como a energia é usada e onde há oportunidades de otimização." },
    ],
    ctaEyebrow: "Solicitar análise",
    ctaButtonText: "Solicitar análise",
  },
  {
    slug: "spda",
    title: "SPDA | CG Elétrica",
    description: "Soluções de inspeção e testes de SPDA para garantir a proteção contra descargas atmosféricas e a segurança das instalações.",
    whatsappMessage: "Olá, gostaria de solicitar informações sobre SPDA.",
    heroTitle: "Testes de SPDA",
    heroLead: "Avaliação, inspeção e documentação de sistemas de proteção contra descargas atmosféricas.",
    benefitText: "Redução de riscos de danos causados por descargas atmosféricas e maior segurança da instalação.",
    quandoText: "Quando a instalação precisa verificar a eficácia do sistema de proteção, identificar irregularidades ou atender requisitos de segurança.",
    executaList: [
      "Inspeção do sistema SPDA;",
      "Testes de continuidade e integridade;",
      "Avaliação das condições estruturais e elétricas;",
      "Documentação técnica e recomendações.",
    ],
    aplicacoesText: "Prédios, indústrias, instalações comerciais e estruturas com necessidade de proteção contra descargas atmosféricas.",
    processoList: [
      "Inspeção do sistema existente;",
      "Levantamento de condições e componentes;",
      "Execução de testes e medições relevantes;",
      "Diagnóstico técnico e relato de não conformidades;",
      "Entrega com orientações para adequação.",
    ],
    beneficiosList: [
      "Segurança da estrutura e usuários;",
      "Identificação de riscos antes de falhas;",
      "Melhor manutenção e confiabilidade;",
      "Documentação para planejamento e adequação.",
    ],
    responsabilidadeText: "As soluções são conduzidas com critérios técnicos e documentação orientada à segurança de instalações e processos.",
    faq: [
      { pergunta: "Como saber se o sistema precisa de teste?", resposta: "Quando há manutenção periódica, alterações na estrutura ou qualquer suspeita de falha ou não conformidade." },
      { pergunta: "Testes são obrigatórios?", resposta: "Em muitos casos, sim, para garantir continuidade de proteção e atendimento às boas práticas e normas relevantes." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "areas-classificadas",
    title: "Áreas Classificadas Ex | CG Elétrica",
    description: "Projetos e adequações para áreas classificadas Ex, com análise técnica, segurança e engenharia aplicada a atmosferas potencialmente explosivas.",
    whatsappMessage: "Olá, gostaria de conversar sobre áreas classificadas Ex.",
    heroTitle: "Áreas classificadas Ex",
    heroLead: "Projetos, análise e adequações para ambientes com atmosferas potencialmente explosivas.",
    benefitText: "Segurança em instalações de alta exigência e redução de riscos em ambientes classificáveis.",
    quandoText: "Quando há presença de atmosferas potencialmente explosivas e necessidade de sistemas elétricos específicos, seguros e adequados ao ambiente.",
    executaList: [
      "Projeto e análise de instalações Ex;",
      "Especificação de materiais e componentes;",
      "Adequações técnicas de segurança;",
      "Suporte para operação confiável em ambientes críticos.",
    ],
    aplicacoesText: "Indústrias, instalações com misturas inflamáveis e ambientes que exigem critérios específicos de projeto e execução.",
    processoList: [
      "Diagnóstico do ambiente e condições operacionais;",
      "Análise das exigências de segurança e comissionamento;",
      "Definição do projeto e especificações;",
      "Execução e validação técnica;",
      "Entrega com documentação e orientação.",
    ],
    beneficiosList: [
      "Segurança em ambiente crítico;",
      "Conformidade e confiabilidade técnica;",
      "Menor risco de falhas e acidentes;",
      "Boa base para operação e manutenção.",
    ],
    responsabilidadeText: "O planejamento e a execução deste tipo de solução são conduzidos com rigor técnico e atenção às exigências da instalação e do ambiente.",
    faq: [
      { pergunta: "Qual o principal foco?", resposta: "Reduzir riscos em ambientes com atmosferas potencialmente explosivas." },
      { pergunta: "O projeto exige rigidez técnica?", resposta: "Sim. O escopo deve considerar especificações e critérios de segurança muito particulares." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "sistemas-fotovoltaicos",
    title: "Sistemas Fotovoltaicos | CG Elétrica",
    description: "Sistemas fotovoltaicos On-Grid, Off-Grid e Híbridos com estudo, dimensionamento e integração para geração de energia confiável.",
    whatsappMessage: "Olá, gostaria de conversar sobre um sistema fotovoltaico.",
    heroTitle: "Sistemas fotovoltaicos",
    heroLead: "Estudo, dimensionamento e integração de soluções On-Grid, Off-Grid e Híbridas.",
    benefitText: "Geração de energia com melhor uso dos recursos e integração segura com a instalação.",
    quandoText: "Quando a empresa busca reduzir dependência da rede, otimizar o consumo ou garantir operação mais estável em aplicações específicas.",
    executaList: [
      "Estudo técnico e viabilidade;",
      "Dimensionamento do sistema;",
      "Integração com infraestrutura existente;",
      "Planejamento de confiabilidade e operação.",
    ],
    aplicacoesText: "Empreendimentos comerciais, industriais, condomínios e instalações que buscam energia mais eficiente e autônoma.",
    processoList: [
      "Diagnóstico de consumo e demanda;",
      "Definição de configuração On-Grid, Off-Grid ou Híbrida;",
      "Dimensionamento e avaliação de integração;",
      "Documentação técnica e orientação de execução;",
      "Suporte à operação e eficiência.",
    ],
    beneficiosList: [
      "Eficiência energética;",
      "Menor dependência externa;",
      "Confiabilidade e planejamento técnico;",
      "Integração com a operação da instalação.",
    ],
    responsabilidadeText: "A solução é pensada com base no consumo e nas exigências da instalação, com atenção à viabilidade, segurança e integração.",
    faq: [
      { pergunta: "Qual configuração é melhor?", resposta: "Depende do perfil de consumo, da necessidade de autonomia e da infraestrutura disponível." },
      { pergunta: "É viável para operação crítica?", resposta: "Sim, com análise técnica adequada e definição do sistema correto." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "manutencao-eletrica",
    title: "Manutenção Elétrica de Alta e Baixa Tensão | CG Elétrica",
    description: "Manutenção elétrica de alta e baixa tensão com diagnóstico, inspeção e ações para continuidade operacional e redução de falhas.",
    whatsappMessage: "Olá, gostaria de solicitar manutenção elétrica de alta e baixa tensão.",
    heroTitle: "Manutenção elétrica de alta e baixa tensão",
    heroLead: "Assessoria e manutenção para sistemas, quadros, equipamentos e infraestrutura elétrica.",
    benefitText: "Maior segurança, confiabilidade e continuidade operacional dos sistemas elétricos.",
    quandoText: "Quando há necessidade de inspeção, prevenção, correção de falhas ou garantia de desempenho nos sistemas de distribuição e alimentação.",
    executaList: [
      "Inspeção de sistemas e equipamentos;",
      "Manutenção preventiva e corretiva;",
      "Diagnóstico de quadros, infraestrutura e cargas;",
      "Recomendação de ações para confiabilidade.",
    ],
    aplicacoesText: "Instalações comerciais, industriais, sistemas de distribuição e estruturas com operação contínua e demanda técnica.",
    processoList: [
      "Identificação das condições da instalação;",
      "Inspeção de componentes e sistemas;",
      "Diagnóstico técnico e preservação do funcionamento;",
      "Execução das ações corretivas ou preventivas;",
      "Entrega de documentação e orientação.",
    ],
    beneficiosList: [
      "Segurança e confiabilidade;",
      "Prevenção de falhas e interrupções;",
      "Maior vida útil de equipamentos;",
      "Operação mais estável e previsível.",
    ],
    responsabilidadeText: "As ações são avaliadas e executadas com foco em segurança, eficiência e continuidade do sistema elétrico.",
    faq: [
      { pergunta: "Quando a manutenção deve começar?", resposta: "Se a instalação apresenta desgaste, falhas recorrentes, aquecimento ou queda de desempenho." },
      { pergunta: "É necessário parar a operação?", resposta: "Depende do nível de risco e do tipo de solução, mas a análise é sempre orientada à segurança." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "nr10",
    title: "Adequação NR-10 | CG Elétrica",
    description: "Adequação NR-10, análise de segurança elétrica e identificação de não conformidades com soluções técnicas para instalações.",
    whatsappMessage: "Olá, gostaria de solicitar uma análise de adequação NR-10.",
    heroTitle: "Adequação NR-10",
    heroLead: "Análise técnica para reduzir riscos elétricos, corrigir não conformidades e orientar adequações seguras.",
    benefitText: "Melhor segurança para trabalhadores, instalações e operação contínua da empresa.",
    quandoText: "Quando a instalação apresenta riscos elétricos, não conformidades ou necessidade de adequação às exigências de segurança.",
    executaList: [
      "Análise de instalações elétricas;",
      "Identificação de não conformidades;",
      "Recomendação de adequações técnicas;",
      "Documentação e orientação para correção.",
    ],
    aplicacoesText: "Indústrias, empresas, locais de operação com risco elétrico e instalações que necessitem de revisão técnica.",
    processoList: [
      "Diagnóstico da situação atual;",
      "Avaliação de riscos e conformidade;",
      "Definição das adequações necessárias;",
      "Planejamento de execução e documentação;",
      "Suporte técnico na correção.",
    ],
    beneficiosList: [
      "Maior segurança de operação;",
      "Redução de riscos elétricos;",
      "Melhor conformidade tecnológica e organizacional;",
      "Documentação adequada para gestão.",
    ],
    responsabilidadeText: "A solução é executada com análise técnica, documentação e orientação que apoiam a adequação da instalação conforme a necessidade.",
    faq: [
      { pergunta: "Como sei que preciso de adequação?", resposta: "Quando há condições inseguras, pontos críticos ou necessidade de revisão técnica de conformidade." },
      { pergunta: "É possível planejar a adequação em etapas?", resposta: "Sim, sempre que a operação e o risco permitirem uma estratégia gradual." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "laudos-art",
    title: "Laudos Técnicos com ART | CG Elétrica",
    description: "Laudos técnicos com ART, inspeção, análise e documentação para instalações elétricas com responsabilidade profissional.",
    whatsappMessage: "Olá, gostaria de solicitar um laudo técnico com ART.",
    heroTitle: "Laudos técnicos com ART",
    heroLead: "Inspeção, análise e documentação técnica para suporte à operação, segurança e responsabilidade profissional.",
    benefitText: "Diagnóstico técnico documentado e respaldo para tomada de decisão, adequação e manutenção.",
    quandoText: "Quando existe necessidade de avaliação de condições técnicas, diagnóstico de falhas, documentação para adequações ou suporte a requisitos de operação.",
    executaList: [
      "Inspeção técnica de instalações;",
      "Análise de condições e desempenho;",
      "Diagnóstico de riscos e não conformidades;",
      "Laudo e documentação com ART quando aplicável.",
    ],
    aplicacoesText: "Instalações comerciais, industriais, empreendimentos e sistemas com necessidade de comprovação técnica.",
    processoList: [
      "Levantamento do estado atual da instalação;",
      "Inspeção e coleta de dados;",
      "Análise técnica e identificação de pontos críticos;",
      "Emissão do laudo ou parecer técnico;",
      "Orientação para ação corretiva.",
    ],
    beneficiosList: [
      "Comprovação técnica e segurança;",
      "Documentação para decisão e planejamento;",
      "Redução de riscos operacionais;",
      "Base para adequações e manutenção preventiva.",
    ],
    responsabilidadeText: "Esta solução é realizada com rigor técnico e responsabilidade profissional, conforme a aplicação do escopo e da legislação envolvida.",
    faq: [
      { pergunta: "Quem pode solicitar?", resposta: "Empresas, gestores de imóveis, condomínios e operações que necessitem de laudo técnico." },
      { pergunta: "Qual a diferença entre laudo e parecer?", resposta: "O laudo documenta condições observadas e conclusões; o parecer orienta o diagnóstico e a recomendação prática." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "geradores-ups",
    title: "Geradores e UPS | CG Elétrica",
    description: "Geradores elétricos, Nobreak e UPS para continuidade operacional, proteção e disponibilidade em instalações críticas.",
    whatsappMessage: "Olá, gostaria de conversar sobre geradores ou UPS.",
    heroTitle: "Geradores e UPS",
    heroLead: "Soluções para continuidade, proteção e disponibilidade em sistemas críticos e operações sensíveis.",
    benefitText: "Manter a operação estável e reduzir impactos de interrupções elétricas.",
    quandoText: "Quando a instalação exige continuidade, proteção de sistemas críticos ou solução para interrupções da rede.",
    executaList: [
      "Avaliação da demanda e criticidade;",
      "Suporte para dimensionamento e integração;",
      "Manutenção e diagnóstico de geradores e UPS;",
      "Orienta solução para continuidade operacional.",
    ],
    aplicacoesText: "Data centers, indústria, comércio, condomínios, sistemas com operação contínua e cargas sensíveis.",
    processoList: [
      "Diagnóstico de necessidade e criticidade;",
      "Definição da solução de energia de contingência;",
      "Dimensionamento e avaliação de integração;",
      "Manutenção ou adequação da infraestrutura;",
      "Documentação e orientação operacional.",
    ],
    beneficiosList: [
      "Continuidade operacional;",
      "Proteção de sistemas sensíveis;",
      "Disponibilidade e estabilidade;",
      "Menor impacto de interrupções de energia.",
    ],
    responsabilidadeText: "O desenvolvimento da solução considera as exigências do sistema, o nível de criticidade e a melhor configuração técnica disponível.",
    faq: [
      { pergunta: "Qual a diferença entre gerador e UPS?", resposta: "Gerador atende contingência de energia e o UPS protege cargas sensíveis contra interrupções instantâneas." },
      { pergunta: "Preciso dos dois?", resposta: "Depende da criticidade da carga e do objetivo da instalação." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
  {
    slug: "energia-eolica",
    title: "Distribuição de Rede Elétrica para Energia Eólica | CG Elétrica",
    description: "Soluções técnicas para distribuição de rede elétrica aplicada a sistemas de energia eólica, com foco em confiabilidade, segurança e desempenho.",
    whatsappMessage: "Olá, gostaria de solicitar uma avaliação para distribuição de rede elétrica para energia eólica.",
    heroTitle: "Distribuição de rede elétrica para energia eólica",
    heroLead: "Planejamento e suporte técnico para integração e distribuição segura da energia gerada por sistemas eólicos.",
    benefitText: "Estruturação da rede para distribuição eficiente da energia eólica, com redução de riscos operacionais.",
    quandoText: "Quando o projeto exige conexão, distribuição ou adequação de infraestrutura elétrica para transportar a energia gerada por parques ou sistemas eólicos.",
    executaList: [
      "Diagnóstico técnico da infraestrutura elétrica existente;",
      "Definição de escopo para distribuição da energia gerada;",
      "Apoio no dimensionamento e integração de rede;",
      "Documentação técnica e orientação para execução.",
    ],
    aplicacoesText: "Empreendimentos com geração eólica, operações com necessidade de integração à rede e projetos de expansão energética.",
    processoList: [
      "Levantamento técnico das condições do sistema;",
      "Análise das necessidades de distribuição e integração;",
      "Definição técnica da solução e do escopo;",
      "Orientação de implementação com foco em segurança;",
      "Entrega de diretrizes e documentação técnica.",
    ],
    beneficiosList: [
      "Distribuição elétrica mais segura e confiável;",
      "Melhor desempenho operacional do sistema eólico;",
      "Redução de falhas por incompatibilidade de infraestrutura;",
      "Base técnica para expansão e continuidade da operação.",
    ],
    responsabilidadeText: "A solução é conduzida com critérios de engenharia, conforme o escopo do projeto e requisitos técnicos aplicáveis, com ART quando pertinente.",
    faq: [
      { pergunta: "Essa solução atende projetos novos e existentes?", resposta: "Sim. O escopo pode ser aplicado tanto em novas instalações quanto em adequações de sistemas já em operação." },
      { pergunta: "A CG Elétrica executa apenas consultoria ou também apoio técnico de implementação?", resposta: "A atuação é definida conforme a necessidade do projeto, podendo incluir planejamento técnico e suporte à implementação." },
    ],
    ctaEyebrow: "Solicitar avaliação",
    ctaButtonText: "Solicitar avaliação",
  },
];
